export interface Receta {
  slug: string;
  titulo: string;
  descripcionCorta: string;
  gradiente: string;
  iconColor: string;
  imageUrl?: string;
  tiempo: string;
  dificultad: 'Fácil' | 'Media' | 'Avanzada';
  porciones: number;
  ingredientes: string[];
  pasos: string[];
  productos: string[];
}

export const RECETAS: Receta[] = [
  {
    slug: 'batido-fuerza-glutaprot',
    titulo: 'Batido de Fuerza',
    descripcionCorta: 'Batido nutritivo con plátano y miel, ideal para la recuperación intestinal y fortalecer el sistema inmunológico.',
    gradiente: 'from-[#1f7ec2] to-[#0c447c]',
    iconColor: 'text-sky-200',
    imageUrl: 'https://images.unsplash.com/photo-1594489428504-5c0c480a15fd?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 sobre de Glutaprot-Bio',
      '1 plátano maduro',
      '200 ml de leche o bebida vegetal',
      '1 cucharadita de miel',
      '3–4 cubos de hielo (opcional)',
    ],
    pasos: [
      'Agrega la leche al vaso de la licuadora.',
      'Incorpora el plátano en trozos y la miel.',
      'Añade el sobre de Glutaprot-Bio y mezcla bien.',
      'Licúa a velocidad alta por 30 segundos hasta obtener una mezcla homogénea.',
      'Sirve inmediatamente y consume preferiblemente en ayunas o entre comidas.',
    ],
    productos: ['Glutaprot - Bio'],
  },
  {
    slug: 'yogur-enriquecido-glutaprot',
    titulo: 'Yogur Enriquecido con Frutas',
    descripcionCorta: 'Yogur cremoso con frutas del bosque y Glutaprot-Bio, una opción deliciosa para apoyar la microbiota intestinal.',
    gradiente: 'from-emerald-400 to-teal-600',
    iconColor: 'text-emerald-100',
    imageUrl: 'https://images.unsplash.com/photo-1612182062572-e29c5dfb5eb4?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 sobre de Glutaprot-Bio',
      '150 g de yogur natural sin azúcar',
      '1 puñado de fresas, arándanos o frutas del bosque',
      '1 cucharada de granola (opcional)',
      '1 cucharadita de miel',
    ],
    pasos: [
      'Vierte el yogur en un recipiente hondo.',
      'Añade el sobre de Glutaprot-Bio y mezcla bien con una cuchara hasta integrar.',
      'Incorpora las frutas lavadas y cortadas.',
      'Agrega la miel y la granola por encima.',
      'Sirve frío. Ideal como desayuno o merienda durante el proceso de recuperación.',
    ],
    productos: ['Glutaprot - Bio'],
  },
  {
    slug: 'avena-reconstituyente-glutaprot',
    titulo: 'Avena Reconstituyente',
    descripcionCorta: 'Avena caliente con canela y Glutaprot-Bio, una receta reconfortante para apoyar la recuperación en pacientes con infecciones o mucositis.',
    gradiente: 'from-rose-400 to-pink-600',
    iconColor: 'text-rose-100',
    imageUrl: 'https://images.unsplash.com/photo-1497888329096-51c27beff665?w=600&q=80&auto=format&fit=crop',
    tiempo: '10 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 sobre de Glutaprot-Bio',
      '4 cucharadas de avena en hojuelas',
      '250 ml de leche o bebida vegetal',
      '1 pizca de canela en polvo',
      'Miel o azúcar al gusto',
    ],
    pasos: [
      'Calienta la leche en una olla pequeña a fuego medio.',
      'Agrega las hojuelas de avena y revuelve constantemente por 4–5 minutos hasta espesar.',
      'Retira del fuego y deja enfriar ligeramente (no debe estar hirviendo).',
      'Añade el sobre de Glutaprot-Bio y mezcla bien.',
      'Sirve con canela y miel por encima. Consume tibio.',
    ],
    productos: ['Glutaprot - Bio'],
  },

  // ── Qomplett Kidz ─────────────────────────────────────────────────────────
  {
    slug: 'batido-frutas-kidz',
    titulo: 'Batido de Frutas Tropical',
    descripcionCorta: 'Batido colorido con mango y maracuyá enriquecido con Qomplett Kidz, perfecto para el desayuno o merienda de los más pequeños.',
    gradiente: 'from-yellow-400 to-orange-400',
    iconColor: 'text-yellow-100',
    imageUrl: 'https://images.unsplash.com/photo-1570696516188-ade861b84a49?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Qomplett Kidz',
      '150 ml de jugo de mango natural',
      '50 ml de jugo de maracuyá',
      '100 ml de agua fría',
      '2–3 cubos de hielo',
    ],
    pasos: [
      'Vierte todos los jugos y el agua en la licuadora.',
      'Agrega la medida de Qomplett Kidz.',
      'Licúa a velocidad alta por 20–30 segundos.',
      'Añade hielo y licúa 10 segundos más.',
      'Sirve en un vaso llamativo. Consumir de inmediato.',
    ],
    productos: ['Qomplett Kidz'],
  },
  {
    slug: 'pudin-vainilla-kidz',
    titulo: 'Pudín de Vainilla',
    descripcionCorta: 'Suave pudín de vainilla preparado con Qomplett Kidz, una forma deliciosa de asegurar la nutrición completa del niño.',
    gradiente: 'from-amber-300 to-yellow-500',
    iconColor: 'text-amber-100',
    imageUrl: 'https://images.unsplash.com/photo-1550594645-25c5bd703258?w=600&q=80&auto=format&fit=crop',
    tiempo: '15 min',
    dificultad: 'Fácil',
    porciones: 2,
    ingredientes: [
      '2 medidas de Qomplett Kidz',
      '300 ml de leche entera',
      '1 cucharada de maicena',
      '1 cucharadita de vainilla',
      'Canela en polvo para decorar',
    ],
    pasos: [
      'Disuelve la maicena en 50 ml de leche fría.',
      'Calienta el resto de la leche a fuego medio sin que hierva.',
      'Retira del fuego y deja enfriar 2 minutos.',
      'Agrega Qomplett Kidz, la mezcla de maicena y la vainilla; mezcla bien.',
      'Lleva de nuevo al fuego bajo revolviendo hasta espesar (2–3 min).',
      'Vierte en moldes y refrigera 30 minutos. Sirve con canela.',
    ],
    productos: ['Qomplett Kidz'],
  },
  {
    slug: 'avena-chocolate-kidz',
    titulo: 'Avena con Chocolate',
    descripcionCorta: 'Avena cremosa con toque de cacao y Qomplett Kidz — un desayuno nutritivo que los niños no van a querer dejar.',
    gradiente: 'from-amber-700 to-yellow-600',
    iconColor: 'text-amber-100',
    imageUrl: 'https://images.unsplash.com/photo-1505253827648-b4de98bc66b4?w=600&q=80&auto=format&fit=crop',
    tiempo: '10 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Qomplett Kidz',
      '4 cucharadas de avena en hojuelas',
      '220 ml de leche',
      '1 cucharadita de cacao en polvo sin azúcar',
      'Miel o azúcar morena al gusto',
    ],
    pasos: [
      'Calienta la leche con el cacao en polvo revolviendo hasta disolver.',
      'Agrega la avena y cocina a fuego medio 4–5 minutos.',
      'Retira del fuego y espera que baje a temperatura tibia.',
      'Añade la medida de Qomplett Kidz y mezcla bien.',
      'Endulza al gusto y sirve de inmediato.',
    ],
    productos: ['Qomplett Kidz'],
  },

  // ── Qomplett Oncare ───────────────────────────────────────────────────────
  {
    slug: 'batido-manzana-oncare',
    titulo: 'Batido Suave de Manzana',
    descripcionCorta: 'Batido de manzana con Qomplett Oncare, de sabor delicado y fácil digestión, ideal para pacientes oncológicos con poco apetito.',
    gradiente: 'from-green-400 to-teal-500',
    iconColor: 'text-green-100',
    imageUrl: 'https://images.unsplash.com/photo-1534336810865-0beae4c81278?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Qomplett Oncare',
      '150 ml de jugo de manzana natural colado',
      '100 ml de agua fría',
      '1 cucharadita de miel (opcional)',
    ],
    pasos: [
      'Mezcla el jugo de manzana con el agua en un vaso.',
      'Añade la medida de Qomplett Oncare.',
      'Revuelve enérgicamente con una cuchara o batidor de mano hasta disolver.',
      'Agrega miel si se desea mayor dulzor.',
      'Servir frío. Consumir a pequeños sorbos a lo largo del día.',
    ],
    productos: ['Qomplett Oncare'],
  },
  {
    slug: 'crema-papa-oncare',
    titulo: 'Crema de Papa Enriquecida',
    descripcionCorta: 'Crema suave de papa con Qomplett Oncare integrada, fácil de ingerir y con el aporte calórico-proteico que el paciente necesita.',
    gradiente: 'from-lime-500 to-green-600',
    iconColor: 'text-lime-100',
    imageUrl: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=600&q=80&auto=format&fit=crop',
    tiempo: '20 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Qomplett Oncare',
      '1 papa mediana pelada y cortada',
      '200 ml de caldo de pollo suave (bajo en sodio)',
      '1 cucharada de aceite de oliva',
      'Sal al gusto',
    ],
    pasos: [
      'Hierve la papa en el caldo hasta que esté muy blanda (15 min).',
      'Licúa la papa con el caldo hasta obtener una crema homogénea.',
      'Deja enfriar hasta temperatura tibia.',
      'Agrega Qomplett Oncare y el aceite de oliva; mezcla bien.',
      'Sirve tibio. Evitar temperaturas altas para preservar los nutrientes.',
    ],
    productos: ['Qomplett Oncare'],
  },
  {
    slug: 'gelatina-fruta-oncare',
    titulo: 'Gelatina con Frutas Suaves',
    descripcionCorta: 'Gelatina ligera con durazno y Qomplett Oncare, fácil de consumir y con aporte nutricional para pacientes con dificultades para masticar.',
    gradiente: 'from-teal-400 to-cyan-500',
    iconColor: 'text-teal-100',
    imageUrl: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600&q=80&auto=format&fit=crop',
    tiempo: '10 min + reposo',
    dificultad: 'Fácil',
    porciones: 2,
    ingredientes: [
      '1 medida de Qomplett Oncare',
      '1 sobre de gelatina sin sabor (7 g)',
      '250 ml de jugo de durazno natural',
      '150 ml de agua caliente',
      '2–3 duraznos en almíbar sin semilla (opcional)',
    ],
    pasos: [
      'Disuelve la gelatina sin sabor en el agua caliente.',
      'Agrega el jugo de durazno y mezcla.',
      'Espera que la mezcla baje a temperatura tibia.',
      'Añade Qomplett Oncare y bate bien con batidor de mano.',
      'Vierte en moldes, agrega trozos de durazno si se desea.',
      'Refrigera al menos 2 horas antes de servir.',
    ],
    productos: ['Qomplett Oncare'],
  },

  // ── Qomplett Recover ─────────────────────────────────────────────────────
  {
    slug: 'batido-platano-recover',
    titulo: 'Batido de Plátano y Miel',
    descripcionCorta: 'Batido energético con plátano y Qomplett Recover para apoyar la recuperación muscular y tisular después de procedimientos o cirugías.',
    gradiente: 'from-orange-400 to-red-500',
    iconColor: 'text-orange-100',
    imageUrl: 'https://images.unsplash.com/photo-1563417994892-38ee47f9d1f2?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Qomplett Recover',
      '1 plátano maduro',
      '200 ml de leche entera o bebida vegetal',
      '1 cucharadita de miel',
      'Hielo al gusto',
    ],
    pasos: [
      'Coloca el plátano en trozos en la licuadora.',
      'Agrega la leche, la miel y la medida de Qomplett Recover.',
      'Licúa a velocidad alta por 30 segundos.',
      'Agrega hielo y licúa 10 segundos más.',
      'Consumir preferiblemente tras el desayuno o en la merienda.',
    ],
    productos: ['Qomplett Recover'],
  },
  {
    slug: 'sopa-zanahoria-recover',
    titulo: 'Sopa Crema de Zanahoria',
    descripcionCorta: 'Reconfortante crema de zanahoria enriquecida con Qomplett Recover para pacientes en proceso de cicatrización o recuperación postquirúrgica.',
    gradiente: 'from-red-400 to-orange-500',
    iconColor: 'text-red-100',
    imageUrl: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?w=600&q=80&auto=format&fit=crop',
    tiempo: '25 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Qomplett Recover',
      '2 zanahorias medianas peladas',
      '200 ml de caldo de verduras',
      '1 cucharada de aceite de oliva',
      'Sal y pimienta al gusto',
    ],
    pasos: [
      'Cuece las zanahorias en el caldo hasta que estén muy blandas (20 min).',
      'Licúa las zanahorias con el caldo hasta obtener una crema suave.',
      'Deja enfriar hasta temperatura tibia.',
      'Incorpora Qomplett Recover y el aceite de oliva; mezcla bien.',
      'Sazona y sirve tibio. Ideal en el almuerzo o cena durante la recuperación.',
    ],
    productos: ['Qomplett Recover'],
  },
  {
    slug: 'yogur-granola-recover',
    titulo: 'Yogur con Granola y Frutos Rojos',
    descripcionCorta: 'Bowl de yogur con granola, frutos rojos y Qomplett Recover — desayuno completo que aporta proteína y colágeno para la regeneración de tejidos.',
    gradiente: 'from-pink-500 to-rose-600',
    iconColor: 'text-pink-100',
    imageUrl: 'https://images.unsplash.com/photo-1571230389215-b34a89739ef1?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Qomplett Recover',
      '150 g de yogur griego natural',
      '2 cucharadas de granola',
      '1 puñado de frutos rojos (fresas, arándanos, frambuesas)',
      '1 cucharadita de miel',
    ],
    pasos: [
      'Vierte el yogur en un tazón.',
      'Agrega la medida de Qomplett Recover y mezcla bien.',
      'Distribuye los frutos rojos por encima.',
      'Añade la granola y termina con un hilo de miel.',
      'Consumir de inmediato como desayuno completo.',
    ],
    productos: ['Qomplett Recover'],
  },

  // ── Qomplett Protein ─────────────────────────────────────────────────────
  {
    slug: 'batido-proteico-chocolate',
    titulo: 'Batido Proteico de Chocolate',
    descripcionCorta: 'Clásico batido de chocolate con Qomplett Protein, ideal para la recuperación muscular después del ejercicio o como suplemento diario de proteína.',
    gradiente: 'from-stone-600 to-amber-800',
    iconColor: 'text-stone-200',
    imageUrl: 'https://images.unsplash.com/photo-1542444592-0d5997f202eb?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Qomplett Protein',
      '250 ml de leche entera o bebida de avena',
      '1 cucharadita de cacao en polvo sin azúcar',
      '1 cucharada de mantequilla de maní (opcional)',
      'Hielo al gusto',
    ],
    pasos: [
      'Coloca la leche, el cacao y la mantequilla de maní en la licuadora.',
      'Agrega la medida de Qomplett Protein.',
      'Licúa a velocidad alta 30 segundos hasta homogeneizar.',
      'Agrega hielo y procesa 10 segundos más.',
      'Consumir dentro de los 30 minutos posteriores al entrenamiento.',
    ],
    productos: ['Qomplett Protein'],
  },
  {
    slug: 'tortitas-proteicas-avena',
    titulo: 'Tortitas de Avena Proteicas',
    descripcionCorta: 'Tortitas esponjosas de avena con Qomplett Protein, una opción de desayuno o merienda alta en proteína y de fácil preparación.',
    gradiente: 'from-amber-500 to-yellow-600',
    iconColor: 'text-amber-100',
    imageUrl: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&q=80&auto=format&fit=crop',
    tiempo: '15 min',
    dificultad: 'Media',
    porciones: 2,
    ingredientes: [
      '1 medida de Qomplett Protein',
      '6 cucharadas de avena en hojuelas',
      '2 huevos',
      '100 ml de leche',
      '1 cucharadita de polvo para hornear',
      'Aceite en spray para cocinar',
    ],
    pasos: [
      'Mezcla la avena, Qomplett Protein y el polvo para hornear en un bowl.',
      'Bate los huevos con la leche e incorpóralos a la mezcla seca.',
      'Revuelve hasta obtener una masa homogénea (puede reposar 2 min).',
      'Calienta una sartén a fuego medio y aplica aceite en spray.',
      'Vierte porciones de masa y cocina 2–3 min por lado hasta dorar.',
      'Sirve con fruta fresca o miel.',
    ],
    productos: ['Qomplett Protein'],
  },
  {
    slug: 'bowl-proteico-quinoa',
    titulo: 'Bowl de Quinoa Proteico',
    descripcionCorta: 'Bowl completo de quinoa con vegetales y Qomplett Protein en aderezo cremoso — comida funcional para mantener la masa muscular.',
    gradiente: 'from-violet-500 to-purple-600',
    iconColor: 'text-violet-100',
    imageUrl: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=600&q=80&auto=format&fit=crop',
    tiempo: '20 min',
    dificultad: 'Media',
    porciones: 1,
    ingredientes: [
      '1 medida de Qomplett Protein',
      '80 g de quinoa cocida',
      '1/2 aguacate en rebanadas',
      '1 puñado de espinaca baby',
      '1/2 tomate en cubos',
      '2 cucharadas de yogur griego para el aderezo',
      'Sal, limón y aceite de oliva',
    ],
    pasos: [
      'Cocina la quinoa según las instrucciones del paquete y deja enfriar.',
      'Mezcla Qomplett Protein con el yogur griego, limón y una pizca de sal para el aderezo.',
      'En un tazón, coloca la quinoa como base.',
      'Agrega la espinaca, el tomate y el aguacate.',
      'Vierte el aderezo proteico por encima.',
      'Sirve de inmediato. Ideal como almuerzo post-entrenamiento.',
    ],
    productos: ['Qomplett Protein'],
  },

  // ── Livenpro ──────────────────────────────────────────────────────────────
  {
    slug: 'batido-detox-manzana-livenpro',
    titulo: 'Batido Detox de Manzana',
    descripcionCorta: 'Batido fresco de manzana verde con Livenpro, ideal para apoyar la función hepática y la eliminación de toxinas en el día a día.',
    gradiente: 'from-emerald-500 to-teal-600',
    iconColor: 'text-emerald-100',
    imageUrl: 'https://images.unsplash.com/photo-1610970881699-45b0b2049022?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Livenpro',
      '1 manzana verde picada (sin semillas)',
      '200 ml de agua fría o agua de coco',
      'Jugo de 1/2 limón',
      '1 cucharadita de jengibre rallado (opcional)',
    ],
    pasos: [
      'Lava y pica la manzana verde en trozos pequeños.',
      'Coloca la manzana, el agua y el jugo de limón en la licuadora.',
      'Licúa a velocidad alta por 30 segundos.',
      'Agrega la medida de Livenpro y el jengibre.',
      'Mezcla 10 segundos más y sirve frío. Consumir preferiblemente en ayunas.',
    ],
    productos: ['Livenpro'],
  },
  {
    slug: 'sopa-verduras-livenpro',
    titulo: 'Crema de Verduras con Livenpro',
    descripcionCorta: 'Crema suave de zanahoria y apio enriquecida con Livenpro, reconfortante y depurativa para apoyar el hígado durante la recuperación.',
    gradiente: 'from-lime-500 to-emerald-600',
    iconColor: 'text-lime-100',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80&auto=format&fit=crop',
    tiempo: '25 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Livenpro',
      '1 zanahoria mediana',
      '1 tallo de apio',
      '1/2 cebolla',
      '250 ml de caldo de verduras bajo en sodio',
      '1 cucharada de aceite de oliva',
      'Sal y cúrcuma al gusto',
    ],
    pasos: [
      'Pica las verduras en trozos y cocínalas en el caldo por 15 minutos hasta que estén blandas.',
      'Licúa todo hasta obtener una crema homogénea.',
      'Deja enfriar hasta temperatura tibia.',
      'Añade Livenpro, el aceite de oliva y la cúrcuma; mezcla bien.',
      'Sirve tibio. Evitar temperaturas altas para preservar los nutrientes.',
    ],
    productos: ['Livenpro'],
  },
  {
    slug: 'agua-limon-livenpro',
    titulo: 'Agua de Limón con Livenpro',
    descripcionCorta: 'Bebida refrescante de agua con limón y Livenpro, la forma más sencilla y diaria de apoyar la salud hepática sin alterar la rutina.',
    gradiente: 'from-yellow-400 to-lime-500',
    iconColor: 'text-yellow-100',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&q=80&auto=format&fit=crop',
    tiempo: '3 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Livenpro',
      '300 ml de agua fría o tibia',
      'Jugo de 1 limón',
      '1 cucharadita de miel (opcional)',
      'Hielo al gusto',
    ],
    pasos: [
      'Exprime el limón en el vaso.',
      'Agrega el agua y la miel; mezcla bien.',
      'Incorpora la medida de Livenpro y revuelve hasta disolver.',
      'Añade hielo si se desea consumir frío.',
      'Tomar preferiblemente en ayunas o entre comidas.',
    ],
    productos: ['Livenpro'],
  },

  // ── Fibra ─────────────────────────────────────────────────────────────────
  {
    slug: 'smoothie-fibra-frutas-bosque',
    titulo: 'Smoothie de Fibra con Frutos del Bosque',
    descripcionCorta: 'Smoothie cargado de antioxidantes y Fibra para activar el tránsito intestinal y comenzar el día con energía.',
    gradiente: 'from-purple-500 to-indigo-600',
    iconColor: 'text-purple-100',
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Fibra',
      '100 g de frutos del bosque congelados (arándanos, moras, frambuesas)',
      '200 ml de leche o bebida vegetal',
      '1 cucharada de semillas de chía',
      '1 cucharadita de miel',
    ],
    pasos: [
      'Coloca los frutos del bosque y la leche en la licuadora.',
      'Licúa a velocidad alta por 30 segundos.',
      'Agrega la medida de Fibra, las semillas de chía y la miel.',
      'Mezcla 10 segundos más a velocidad baja.',
      'Sirve inmediatamente.',
    ],
    productos: ['Livenpro Fibra'],
  },
  {
    slug: 'avena-nocturna-fibra',
    titulo: 'Avena Nocturna con Fibra',
    descripcionCorta: 'Avena preparada en frío con Fibra y plátano, sin cocción, que optimiza la digestión durante el descanso nocturno.',
    gradiente: 'from-amber-400 to-orange-500',
    iconColor: 'text-amber-100',
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min + reposo',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Fibra',
      '5 cucharadas de avena en hojuelas',
      '200 ml de leche o bebida de avena',
      '1/2 plátano en rodajas',
      '1 cucharadita de miel',
      'Canela al gusto',
    ],
    pasos: [
      'Mezcla la avena, la leche y la miel en un frasco con tapa.',
      'Agrega la medida de Fibra y revuelve bien.',
      'Coloca el plátano en rodajas encima.',
      'Cierra el frasco y refrigera toda la noche (mínimo 6 horas).',
      'Al servir, añade canela y consume frío o a temperatura ambiente.',
    ],
    productos: ['Livenpro Fibra'],
  },
  {
    slug: 'yogur-fibra-fruta',
    titulo: 'Yogur con Fibra y Fruta Fresca',
    descripcionCorta: 'Bowl de yogur con Fibra, kiwi y fresas — desayuno ligero que cuida el tránsito intestinal sin sacrificar el sabor.',
    gradiente: 'from-green-400 to-teal-500',
    iconColor: 'text-green-100',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Fibra',
      '150 g de yogur natural sin azúcar',
      '1 kiwi pelado y picado',
      '3–4 fresas en rodajas',
      '1 cucharada de granola',
      '1 cucharadita de miel',
    ],
    pasos: [
      'Vierte el yogur en un tazón.',
      'Agrega la medida de Fibra y mezcla bien hasta integrar.',
      'Distribuye el kiwi y las fresas por encima.',
      'Añade la granola y la miel como toque final.',
      'Consumir de inmediato.',
    ],
    productos: ['Livenpro Fibra'],
  },

  // ── Colágeno ──────────────────────────────────────────────────────────────
  {
    slug: 'batido-colageno-fresas',
    titulo: 'Batido de Colágeno con Fresas',
    descripcionCorta: 'Batido rosado con fresas y Colágeno, rico en vitamina C para potenciar la síntesis de colágeno y mejorar piel, cabello y uñas.',
    gradiente: 'from-rose-400 to-pink-500',
    iconColor: 'text-rose-100',
    imageUrl: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Colágeno',
      '150 g de fresas frescas o congeladas',
      '200 ml de leche o bebida de almendras',
      '1 cucharadita de miel',
      'Jugo de 1/2 limón',
      '3–4 cubos de hielo',
    ],
    pasos: [
      'Lava y desinfecta las fresas; retira el pedúnculo.',
      'Coloca las fresas, la leche, la miel y el jugo de limón en la licuadora.',
      'Licúa a velocidad alta por 30 segundos.',
      'Agrega la medida de Colágeno y los cubos de hielo.',
      'Mezcla 10 segundos más y sirve de inmediato.',
    ],
    productos: ['Livenpro Colágeno'],
  },
  {
    slug: 'infusion-dorada-colageno',
    titulo: 'Infusión Dorada de Colágeno',
    descripcionCorta: 'Bebida caliente de cúrcuma y jengibre con Colágeno — antiinflamatoria y reparadora para piel y articulaciones.',
    gradiente: 'from-amber-400 to-yellow-500',
    iconColor: 'text-amber-100',
    imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&q=80&auto=format&fit=crop',
    tiempo: '10 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Colágeno',
      '250 ml de leche de coco o leche entera',
      '1/2 cucharadita de cúrcuma en polvo',
      '1/4 cucharadita de jengibre en polvo',
      '1 pizca de pimienta negra',
      '1 cucharadita de miel',
    ],
    pasos: [
      'Calienta la leche de coco a fuego bajo sin que hierva.',
      'Agrega la cúrcuma, el jengibre y la pimienta negra; mezcla bien.',
      'Retira del fuego y deja enfriar hasta temperatura tibia.',
      'Añade la medida de Colágeno y la miel; remueve hasta disolver.',
      'Sirve caliente.',
    ],
    productos: ['Livenpro Colágeno'],
  },
  {
    slug: 'bowl-frutas-colageno',
    titulo: 'Bowl de Frutas con Colágeno',
    descripcionCorta: 'Bowl colorido de frutas frescas con yogur y Colágeno — desayuno que nutre la piel desde adentro con vitaminas y colágeno.',
    gradiente: 'from-fuchsia-400 to-pink-500',
    iconColor: 'text-fuchsia-100',
    imageUrl: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=600&q=80&auto=format&fit=crop',
    tiempo: '5 min',
    dificultad: 'Fácil',
    porciones: 1,
    ingredientes: [
      '1 medida de Colágeno',
      '150 g de yogur griego natural',
      '1/2 mango en cubos',
      '1 kiwi en rodajas',
      '1 puñado de arándanos',
      '1 cucharada de almendras laminadas',
      '1 cucharadita de miel',
    ],
    pasos: [
      'Mezcla el yogur griego con la medida de Colágeno en un tazón.',
      'Distribuye las frutas ordenadamente encima (mango, kiwi, arándanos).',
      'Añade las almendras laminadas.',
      'Termina con un hilo de miel por encima.',
      'Consumir de inmediato.',
    ],
    productos: ['Livenpro Colágeno'],
  },
];
